# Generated by Django 6.1 on 2026-08-07 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('POLICE', 'Police'), ('FIRE', 'Fire Brigade'), ('AMBULANCE', 'Ambulance'), ('DISASTER', 'Disaster Management'), ('HELPLINE', 'General Helpline')], db_index=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'emergency_contacts',
            },
        ),
        migrations.CreateModel(
            name='EmergencyIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('FIRE', 'Fire'), ('MEDICAL', 'Medical Emergency'), ('ACCIDENT', 'Road Accident'), ('FLOOD', 'Flooding'), ('EARTHQUAKE', 'Earthquake'), ('CIVIL_UNREST', 'Civil Unrest'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESPONDING', 'Responding'), ('CONTAINED', 'Contained'), ('RESOLVED', 'Resolved')], db_index=True, default='REPORTED', max_length=15)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_incidents',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=20, unique=True)),
                ('responder_type', models.CharField(choices=[('POLICE', 'Police Unit'), ('FIRE', 'Fire Unit'), ('AMBULANCE', 'Ambulance'), ('RESCUE', 'Rescue Team'), ('DISASTER', 'Disaster Response')], db_index=True, max_length=15)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('DISPATCHED', 'Dispatched'), ('ON_SCENE', 'On Scene'), ('RETURNING', 'Returning')], db_index=True, default='AVAILABLE', max_length=15)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'responders',
            },
        ),
        migrations.CreateModel(
            name='IncidentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='emergency.emergencyincident')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='emergency.responder')),
            ],
            options={
                'db_table': 'incident_assignments',
            },
        ),
        migrations.AddIndex(
            model_name='emergencyincident',
            index=models.Index(fields=['status', 'severity'], name='emergency_i_status_2d195a_idx'),
        ),
    ]
