# Generated by Django 6.1 on 2026-08-08 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_remove_emergencyincident_address_and_more'),
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, default='WARNING', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published (Upcoming)'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, help_text='If null, applies to the entire state.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_alerts', to='geography.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emergency_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'severity', 'city'], name='emergency_a_status_4fb706_idx')],
            },
        ),
    ]
