# Generated by Django 6.1 on 2026-08-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_emergencyalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyincident',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this data was generated by the simulator'),
        ),
        migrations.AddField(
            model_name='emergencyincident',
            name='source',
            field=models.CharField(db_index=True, default='API', help_text='Source of data: API, SIMULATOR, MANUAL', max_length=50),
        ),
    ]
