# Generated by Django 6.1 on 2026-08-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_city_ref_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('ON_TASK', 'On Task'), ('OFFLINE', 'Offline'), ('ON_LEAVE', 'On Leave')], default='AVAILABLE', help_text='Operational availability for field workers', max_length=20),
        ),
    ]
