# Generated by Django 6.1 on 2026-08-08 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_availability'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='state_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='geography.state'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zone_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='geography.zone'),
        ),
    ]
