# Generated by Django 6.1 on 2026-08-07 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('road_type', models.CharField(choices=[('HIGHWAY', 'Highway'), ('ARTERIAL', 'Arterial'), ('LOCAL', 'Local')], default='ARTERIAL', max_length=20)),
                ('speed_limit_kmh', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'traffic_zones',
            },
        ),
        migrations.CreateModel(
            name='TrafficIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('BREAKDOWN', 'Vehicle Breakdown'), ('ROADWORK', 'Road Works'), ('FLOODING', 'Road Flooding'), ('OBSTRUCTION', 'Obstruction'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLEARED', 'Cleared'), ('MONITORING', 'Under Monitoring')], db_index=True, default='ACTIVE', max_length=15)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='traffic.trafficzone')),
            ],
            options={
                'db_table': 'traffic_incidents',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.PositiveSmallIntegerField(help_text='Vehicles per km, 0–100 scale')),
                ('avg_speed_kmh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('congestion_level', models.CharField(choices=[('FREE', 'Free Flow'), ('MODERATE', 'Moderate'), ('HEAVY', 'Heavy'), ('JAMMED', 'Jammed')], db_index=True, default='FREE', max_length=10)),
                ('incident_flag', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='traffic.trafficzone')),
            ],
            options={
                'db_table': 'traffic_readings',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['zone', 'recorded_at'], name='traffic_rea_zone_id_e71836_idx')],
            },
        ),
    ]
