# Generated by Django 6.1 on 2026-08-08 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficzone',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='trafficzone',
            name='location_lng',
        ),
        migrations.AddField(
            model_name='trafficzone',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_zones', to='geography.zone'),
        ),
    ]
