# Generated by Django 6.1 on 2026-08-07 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AQIStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('area_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aqi_stations',
            },
        ),
        migrations.CreateModel(
            name='PollutionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqi_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved')], db_index=True, default='ACTIVE', max_length=10)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='pollution.aqistation')),
            ],
            options={
                'db_table': 'pollution_alerts',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='AQIReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm25', models.DecimalField(decimal_places=2, help_text='PM2.5 µg/m³', max_digits=7)),
                ('pm10', models.DecimalField(decimal_places=2, help_text='PM10 µg/m³', max_digits=7)),
                ('co2', models.DecimalField(blank=True, decimal_places=2, help_text='CO2 ppm', max_digits=8, null=True)),
                ('no2', models.DecimalField(blank=True, decimal_places=2, help_text='NO2 µg/m³', max_digits=7, null=True)),
                ('so2', models.DecimalField(blank=True, decimal_places=2, help_text='SO2 µg/m³', max_digits=7, null=True)),
                ('aqi_value', models.DecimalField(db_index=True, decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('GOOD', 'Good (0–50)'), ('MODERATE', 'Moderate (51–100)'), ('UNHEALTHY', 'Unhealthy for Sensitive Groups (101–150)'), ('VERY_UNHEALTHY', 'Very Unhealthy (151–200)'), ('HAZARDOUS', 'Hazardous (200+)')], db_index=True, max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='pollution.aqistation')),
            ],
            options={
                'db_table': 'aqi_readings',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['station', 'recorded_at'], name='aqi_reading_station_622476_idx')],
            },
        ),
    ]
