# Generated by Django 6.1 on 2026-08-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution', '0003_aqireading_is_demo_aqireading_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aqireading',
            name='source',
        ),
        migrations.RemoveField(
            model_name='pollutionalert',
            name='source',
        ),
        migrations.AddField(
            model_name='aqireading',
            name='data_source',
            field=models.CharField(db_index=True, default='API', help_text='Source of data: API, SIMULATOR, MANUAL', max_length=50),
        ),
        migrations.AddField(
            model_name='pollutionalert',
            name='data_source',
            field=models.CharField(db_index=True, default='API', help_text='Source of data: API, SIMULATOR, MANUAL', max_length=50),
        ),
    ]
