# Generated by Django 6.1 on 2026-08-08 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='geography.ward'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('ROAD', 'Road Damage / Pothole'), ('STREET_LIGHT', 'Street Light'), ('GARBAGE', 'Garbage / Illegal Dumping'), ('DRAINAGE', 'Drainage'), ('WATER_SUPPLY', 'Water Supply'), ('WATER_LEAKAGE', 'Water Leakage'), ('ELECTRICITY', 'Electricity'), ('TRAFFIC_SIGNAL', 'Traffic Signal'), ('TRANSPORT', 'Public Transport'), ('ROAD_BLOCKAGE', 'Road Blockage'), ('POLLUTION', 'Pollution'), ('STRAY_ANIMAL', 'Stray Animal'), ('PUBLIC_TOILET', 'Public Toilet'), ('FLOODING', 'Flooding / Waterlogging'), ('CYCLONE', 'Cyclone Damage'), ('OTHER', 'Other')], db_index=True, max_length=30),
        ),
    ]
