# Generated by Django 6.1 on 2026-08-07 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GridZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('max_load_kw', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('total_consumers', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'grid_zones',
            },
        ),
        migrations.CreateModel(
            name='ElectricityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage_v', models.DecimalField(decimal_places=2, max_digits=7)),
                ('current_a', models.DecimalField(decimal_places=2, max_digits=7)),
                ('load_kw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('load_percent', models.DecimalField(decimal_places=2, help_text='Load as % of max', max_digits=5)),
                ('frequency_hz', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('overload_flag', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='electricity.gridzone')),
            ],
            options={
                'db_table': 'electricity_readings',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PowerOutage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(choices=[('EQUIPMENT_FAILURE', 'Equipment Failure'), ('OVERLOAD', 'Overload'), ('MAINTENANCE', 'Planned Maintenance'), ('WEATHER', 'Weather Event'), ('ACCIDENT', 'Accident'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=25)),
                ('description', models.TextField(blank=True)),
                ('affected_households', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESTORING', 'Being Restored'), ('RESOLVED', 'Resolved')], db_index=True, default='ACTIVE', max_length=12)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('estimated_restoration', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outages', to='electricity.gridzone')),
            ],
            options={
                'db_table': 'power_outages',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['status', 'zone'], name='power_outag_status_90d652_idx')],
            },
        ),
    ]
