from django.db import models

class SimulationTrackingModel(models.Model):
    """
    Abstract base class providing tracking fields for IoT events and readings.
    Helps distinguish live data from simulated data in the frontend.
    """
    is_demo = models.BooleanField(
        default=False, 
        help_text="True if this data was generated by the simulator",
        db_index=True
    )
    data_source = models.CharField(
        max_length=50, 
        default="API", 
        help_text="Source of data: API, SIMULATOR, MANUAL",
        db_index=True
    )

    class Meta:
        abstract = True
