# Generated by Django 6.1 on 2026-08-07 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('RESERVOIR', 'Reservoir'), ('BOREWELL', 'Borewell'), ('TREATMENT_PLANT', 'Treatment Plant'), ('TANK', 'Overhead Tank')], db_index=True, max_length=20)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('capacity_million_liters', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'water_sources',
            },
        ),
        migrations.CreateModel(
            name='WaterAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_LEVEL', 'Low Water Level'), ('HIGH_TURBIDITY', 'High Turbidity'), ('PH_ANOMALY', 'pH Anomaly'), ('CONTAMINATION', 'Contamination Detected')], db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved')], db_index=True, default='ACTIVE', max_length=10)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='water.watersource')),
            ],
            options={
                'db_table': 'water_alerts',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_percent', models.DecimalField(decimal_places=2, help_text='Level as % of capacity', max_digits=5)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, help_text='pH 0–14', max_digits=4, null=True)),
                ('turbidity_ntu', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('flow_rate_lps', models.DecimalField(blank=True, decimal_places=3, help_text='Litres per second', max_digits=8, null=True)),
                ('chlorine_ppm', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='water.watersource')),
            ],
            options={
                'db_table': 'water_readings',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['source', 'recorded_at'], name='water_readi_source__b60170_idx')],
            },
        ),
    ]
