# Generated by Django 6.1 on 2026-08-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_remove_watersource_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateralert',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this data was generated by the simulator'),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this data was generated by the simulator'),
        ),
    ]
