# Generated by Django 6.1 on 2026-08-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_wateralert_is_demo_waterreading_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateralert',
            name='data_source',
            field=models.CharField(db_index=True, default='API', help_text='Source of data: API, SIMULATOR, MANUAL', max_length=50),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='data_source',
            field=models.CharField(db_index=True, default='API', help_text='Source of data: API, SIMULATOR, MANUAL', max_length=50),
        ),
    ]
