# Generated by Django 6.1 on 2026-08-07 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bin_type', models.CharField(choices=[('GENERAL', 'General Waste'), ('RECYCLABLE', 'Recyclable'), ('ORGANIC', 'Organic'), ('HAZARDOUS', 'Hazardous')], db_index=True, default='GENERAL', max_length=15)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField(blank=True)),
                ('capacity_liters', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'waste_bins',
            },
        ),
        migrations.CreateModel(
            name='CollectionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assigned_vehicle', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bins', models.ManyToManyField(blank=True, related_name='routes', to='waste.wastebin')),
            ],
            options={
                'db_table': 'collection_routes',
            },
        ),
        migrations.CreateModel(
            name='CollectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_at_collection', models.PositiveSmallIntegerField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste.collectionroute')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_logs', to='waste.wastebin')),
            ],
            options={
                'db_table': 'collection_logs',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteBinReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_percent', models.PositiveSmallIntegerField(help_text='0–100%')),
                ('battery_percent', models.PositiveSmallIntegerField(default=100)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('alert_triggered', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='waste.wastebin')),
            ],
            options={
                'db_table': 'waste_bin_readings',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
