# Generated by Django 6.1 on 2026-08-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_remove_wastebin_address_remove_wastebin_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastebinreading',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this data was generated by the simulator'),
        ),
        migrations.AddField(
            model_name='wastebinreading',
            name='source',
            field=models.CharField(db_index=True, default='API', help_text='Source of data: API, SIMULATOR, MANUAL', max_length=50),
        ),
    ]
