# Generated by Django 6.1 on 2026-08-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_wastebinreading_is_demo_wastebinreading_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastebinreading',
            name='source',
        ),
        migrations.AddField(
            model_name='wastebinreading',
            name='data_source',
            field=models.CharField(db_index=True, default='API', help_text='Source of data: API, SIMULATOR, MANUAL', max_length=50),
        ),
    ]
