# Generated by Django 6.1 on 2026-08-08 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('interval_seconds', models.IntegerField(default=10, help_text='Tick interval in seconds')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'demo_mode_config',
            },
        ),
        migrations.CreateModel(
            name='SimulationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TRAFFIC_ACCIDENT', 'Traffic Accident'), ('BIN_FULL', 'Waste Bin Full'), ('WATER_LEAKAGE', 'Water Leakage'), ('POWER_OUTAGE', 'Power Outage'), ('BUS_BREAKDOWN', 'Bus Breakdown'), ('AQI_HIGH', 'High AQI Alert'), ('EMERGENCY', 'General Emergency'), ('CYCLONE', 'Cyclone Alert')], db_index=True, max_length=50)),
                ('severity', models.CharField(default='WARNING', max_length=15)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_events', to='geography.city')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'simulation_events',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
