# Generated by Django 6.1 on 2026-08-08 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('CIVIC', 'Civic Announcement'), ('TRAFFIC', 'Traffic Notice'), ('WATER', 'Water Maintenance'), ('ELECTRICITY', 'Electricity Maintenance'), ('TRANSPORT', 'Transport Changes'), ('EVENT', 'Public Event'), ('WEATHER', 'Weather Alert'), ('DISASTER', 'Disaster Alert')], default='CIVIC', max_length=20)),
                ('scope_level', models.CharField(choices=[('STATE', 'All Odisha'), ('DISTRICT', 'District'), ('CITY', 'City'), ('WARD', 'Ward')], default='CITY', max_length=20)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
